name: kmrs
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.0.3
  equatable: ^2.0.3
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  font_awesome_flutter: ^9.1.0
  form_inputs:
    path: packages/form_inputs
  formz: ^0.4.0
  google_fonts: ^2.1.0
  meta: ^1.3.0
  very_good_analysis: ^2.3.0
  image_picker: ^0.8.4+4
  provider: ^6.0.1
  flutter_svg: ^1.0.3

  cloud_firestore: ^3.1.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  firebase_storage: ^10.2.3

  webviewx: ^0.2.1

dependency_overrides:
  bloc: ^8.0.2
  bloc_test: ^9.0.2
  flutter_bloc: ^8.0.1

dev_dependencies:
  bloc_test: ^9.0.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
